version: '3.8'

services:
  telegram_bot:
    build:
      context: ./telegram_bot
    depends_on:
      - djangoapp
    networks:
      - mynetwork

  djangoapp:
    build:
      context: ./myapi
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:prod@db:5432/postgres
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=prod
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
    driver: bridge
