version: '3.8'

services:
  telegram_bot:
    build:
      context: ./telegram_bot
    depends_on:
      - django_app

  django_app:
    build:
      context: ./myapi
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:prod@db:5432/postgres
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=prod
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
