# Generated by Django 4.2.6 on 2023-11-04 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ticket_number_start", models.IntegerField(default=100)),
                ("nm_prime", models.IntegerField()),
                ("nm_usual", models.IntegerField()),
                ("date_of_event", models.DateField(default="2023-11-11")),
                (
                    "prices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), null=True, size=None
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Promouter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(max_length=255, null=True)),
                ("full_name", models.CharField(max_length=255, null=True)),
                ("phone_number", models.BigIntegerField(default="99999999", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("ticket_number", models.IntegerField()),
                ("ticket_holder_name", models.CharField(max_length=255)),
                ("ticket_holder_surname", models.CharField(max_length=255)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("prime", "Prime"),
                            ("deposit", "deposit"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                (
                    "date_of_birth",
                    models.CharField(default="2000-01-01", max_length=255),
                ),
                ("price", models.IntegerField(null=True)),
                ("educational_program", models.CharField(max_length=255, null=True)),
                ("educational_course", models.IntegerField(null=True)),
                ("phone_number", models.BigIntegerField(default="99999999", null=True)),
                ("is_refunded", models.BooleanField(default=False)),
            ],
        ),
    ]
