# Generated by Django 4.2.6 on 2023-11-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="nm_deposit",
            field=models.IntegerField(default=0),
        ),
    ]
