# Generated by Django 4.2.6 on 2023-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_ticket_promouter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_path",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
