# Generated by Django 4.2.6 on 2023-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_event_ticket_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo_id",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
