# Generated by Django 4.2.6 on 2024-01-09 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_event_photo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 11, 42, 9, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
