# Generated by Django 4.2.6 on 2024-01-09 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_ticket_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="photo_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="ticket_path",
        ),
        migrations.AddField(
            model_name="event",
            name="nm_bundle",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_id_bundle",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_id_deposit",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_id_prime",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="photo_id_usual",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_path_bundle",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_path_deposit",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_path_prime",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_path_usual",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 18, 12, 47, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("prime", "Prime"),
                    ("deposit", "deposit"),
                    ("bundle", "bundle"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
    ]
