# Generated by Django 4.2.6 on 2024-01-09 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_event_photo_id_remove_event_ticket_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 9, 18, 13, 53, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
