# Generated by Django 4.2.6 on 2024-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_ticket_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
